# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c7d82d4ff9fdba19ae585c3b450b4838637e8cd6e27aca0f82038a8bb62924af540fbc593cee7c652e2dbe37a206dad159dd0aa4a85a10bd2c94941a26534f59

test:
  secret_key_base: 7ff4756107ceb1015c25bcd1183f87ae84b2bf738d605af416337549f5d2be0bde081f886da5c07cc04fd9757c652d20d894c0fbf0d172fffeda6b1c59d4b9af

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
